# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef07938be29f5d1112669a6b14d952dab0c203f29950af99d9c3c750d2e73d4d221df63467e4012c93210c4c2bea6f9ca79a392a3c3b16bb91c3897acd3c852

test:
  secret_key_base: 6bbdfcab2c2c4e6b37f8301d42fc4f677ea2df754c08a4f792f09fe31176c039e49c6ac6360a05a17df7980c93a037d0150d834ee021ebbcefca1aa31239474e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
